import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { PageHeader } from "@/components/assessment-ui";
import { Button } from "@/components/ui/button";
import { Camera, CheckCircle2, ChevronRight, Expand, Mic, MonitorCheck, Wifi } from "lucide-react";
import { useState } from "react";
import { useLocation, useRoute } from "wouter";

type Check = { label: string; detail: string; icon: React.ReactNode; status: "ready" | "pending" | "unavailable" };
export default function PreExamCheck() {
  const [, params] = useRoute("/student/tests/:testId/check"); const [, setLocation] = useLocation(); const { user } = useAuth(); const [camera, setCamera] = useState<"ready" | "pending" | "unavailable">("pending"); const [fullScreen, setFullScreen] = useState<"ready" | "pending" | "unavailable">("pending");
  const testId = params?.testId ?? "";
  const checks: Check[] = [{ label: "Camera", detail: camera === "ready" ? "Camera access granted" : "Camera is optional unless your test requires it", icon: <Camera className="h-4 w-4" />, status: camera }, { label: "Microphone", detail: "Audio is not required by default", icon: <Mic className="h-4 w-4" />, status: "ready" }, { label: "Internet", detail: navigator.onLine ? "Connection detected" : "Offline queue will protect unsent answers", icon: <Wifi className="h-4 w-4" />, status: navigator.onLine ? "ready" : "unavailable" }, { label: "Fullscreen", detail: fullScreen === "ready" ? "Fullscreen is active" : "Can be requested by this browser", icon: <Expand className="h-4 w-4" />, status: fullScreen }];
  const requestCamera = async () => { try { const stream = await navigator.mediaDevices.getUserMedia({ video: true, audio: false }); stream.getTracks().forEach(track => track.stop()); setCamera("ready"); } catch { setCamera("unavailable"); } };
  const requestFullscreen = async () => { try { await document.documentElement.requestFullscreen(); setFullScreen("ready"); } catch { setFullScreen("unavailable"); } };
  if (user?.role !== "student") return <DashboardLayout><div className="min-h-screen bg-[#0e0f16] text-white"><PageHeader eyebrow="Restricted check" title="Student access required" description="Only the assigned student can open an examination system check." /></div></DashboardLayout>;
  return <DashboardLayout><div className="min-h-screen bg-[#0e0f16] text-white"><PageHeader eyebrow="Before you begin" title="System check" description="Confirm your device is ready. Only browser-supported signals are collected, and the test will auto-save answers during any connection interruption." /><div className="mx-auto max-w-3xl px-5 py-7 sm:px-8"><div className="rounded-2xl border border-white/8 bg-white/[0.025] p-5 sm:p-7"><div className="flex gap-3 rounded-xl border border-violet-400/15 bg-violet-500/8 p-4 text-sm leading-6 text-violet-100"><MonitorCheck className="mt-0.5 h-4 w-4 shrink-0" />Your teacher’s security settings determine which checks are required. This screen confirms browser capabilities; it does not promise detection of every form of misconduct.</div><div className="mt-6 space-y-3">{checks.map(check => <div key={check.label} className="flex items-center justify-between gap-4 rounded-xl border border-white/8 bg-white/[0.02] p-4"><div className="flex items-center gap-3"><span className={`grid h-9 w-9 place-items-center rounded-xl ${check.status === "ready" ? "bg-emerald-400/10 text-emerald-300" : check.status === "unavailable" ? "bg-amber-400/10 text-amber-300" : "bg-white/6 text-white/45"}`}>{check.icon}</span><div><p className="text-sm font-medium">{check.label}</p><p className="mt-1 text-xs text-white/45">{check.detail}</p></div></div>{check.status === "ready" ? <CheckCircle2 className="h-5 w-5 text-emerald-300" /> : check.label === "Camera" ? <Button variant="outline" onClick={() => void requestCamera()} className="rounded-lg border-white/10 bg-white/4 text-white hover:bg-white/8 hover:text-white">Check camera</Button> : check.label === "Fullscreen" ? <Button variant="outline" onClick={() => void requestFullscreen()} className="rounded-lg border-white/10 bg-white/4 text-white hover:bg-white/8 hover:text-white">Request fullscreen</Button> : <span className="text-xs text-amber-300">Review</span>}</div>)}</div><Button disabled={!testId} onClick={() => setLocation(`/student/tests/${testId}/attempt`)} className="mt-6 w-full rounded-xl bg-violet-500 text-white hover:bg-violet-400">Start examination<ChevronRight className="h-4 w-4" /></Button></div></div></div></DashboardLayout>;
}
