import { useAuth } from "@/_core/hooks/useAuth";
import DashboardLayout from "@/components/DashboardLayout";
import { PageHeader } from "@/components/assessment-ui";
import { Button } from "@/components/ui/button";
import { trpc } from "@/lib/trpc";
import { Award, BookOpenCheck, ChevronLeft, Clock3, ShieldCheck } from "lucide-react";
import { useLocation, useRoute } from "wouter";

type ReleasedResult = {
  visible: true;
  test: { name: string; subject: string; totalMarks: number };
  attempt: { score: number | null; percentage: number | null; integrityScore: number | null };
  topicPerformance: Array<{ topic: string; percentage: number }>;
};

export default function StudentResult() {
  const [, params] = useRoute("/student/tests/:testId/results"); const [, setLocation] = useLocation(); const { user } = useAuth(); const testId = params?.testId ?? ""; const data = trpc.results.forStudent.useQuery({ testId }, { enabled: Boolean(testId && user?.role === "student") });
  if (user?.role !== "student") return <DashboardLayout><div className="min-h-screen bg-[#0e0f16] text-white"><PageHeader eyebrow="Restricted results" title="Student access required" description="Only a student can view their own released assessment result." /></div></DashboardLayout>;
  const result = data.data; const visibleResult: ReleasedResult | null = result && result.visible && "attempt" in result && "topicPerformance" in result ? result as ReleasedResult : null;
  return <DashboardLayout><div className="min-h-screen bg-[#0e0f16] text-white"><PageHeader eyebrow="Released performance record" title={result?.test.name || "Assessment result"} description="Your result is shown only after your teacher releases it or enables immediate visibility." action={<Button variant="outline" onClick={() => setLocation("/student/tests")} className="rounded-xl border-white/10 bg-white/4 text-white hover:bg-white/8 hover:text-white"><ChevronLeft className="h-4 w-4" />My assessments</Button>} /><div className="mx-auto max-w-5xl px-5 py-7 sm:px-8">{data.isLoading ? <p className="text-sm text-white/45">Loading your result…</p> : !visibleResult ? <div className="grid min-h-72 place-items-center rounded-2xl border border-dashed border-white/10 p-8 text-center"><div><Clock3 className="mx-auto h-6 w-6 text-violet-300" /><p className="mt-4 text-sm font-medium">Result not released yet</p><p className="mt-2 max-w-md text-sm leading-6 text-white/45">Your teacher has not released this assessment result. Your submitted attempt remains securely recorded.</p></div></div> : <><div className="grid gap-4 md:grid-cols-3"><Tile label="Score" value={`${visibleResult.attempt.score?.toFixed(1) ?? 0} / ${visibleResult.test.totalMarks}`} icon={<Award />} /><Tile label="Percentage" value={`${visibleResult.attempt.percentage?.toFixed(1) ?? 0}%`} icon={<BookOpenCheck />} /><Tile label="Integrity review aid" value={`${visibleResult.attempt.integrityScore?.toFixed(1) ?? "—"}/100`} icon={<ShieldCheck />} /></div><section className="mt-5 rounded-2xl border border-white/8 bg-white/[0.025] p-5"><h2 className="text-sm font-medium">Topic performance</h2><p className="mt-1 text-xs text-white/45">Topic measures are calculated from marked objective answers. They are learning signals, not a complete diagnosis.</p>{visibleResult.topicPerformance.length ? <div className="mt-5 space-y-4">{visibleResult.topicPerformance.map(item => <div key={item.topic}><div className="flex justify-between text-sm"><span>{item.topic}</span><span className="text-white/55">{item.percentage.toFixed(1)}%</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white/8"><div className="h-full rounded-full bg-violet-400" style={{ width: `${item.percentage}%` }} /></div></div>)}</div> : <p className="mt-5 text-sm text-white/45">No topic-level objective assessment data is available.</p>}</section><div className="mt-5 rounded-2xl border border-violet-400/15 bg-violet-500/7 p-5"><p className="text-[10px] font-semibold uppercase tracking-[0.14em] text-violet-300">Learning next step</p><p className="mt-3 text-sm leading-6 text-violet-100">Use the topics with the lowest demonstrated score as a starting point for revision. Teachers can provide additional feedback or explanations where that setting has been enabled.</p></div></>}</div></div></DashboardLayout>;
}
function Tile({ label, value, icon }: { label: string; value: string; icon: React.ReactNode }) { return <div className="rounded-2xl border border-white/8 bg-white/[0.03] p-5"><span className="text-violet-300">{icon}</span><p className="mt-4 text-[10px] font-semibold uppercase tracking-[0.13em] text-white/45">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
